# Generated by Django 5.0.6 on 2024-08-06 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contactm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("contacted_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
